import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { BarChart3, Box, CheckCircle2, ChevronDown, CircleDollarSign, ClipboardList, PackagePlus, Users } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const statusLabels: Record<string, string> = { pending: "جديد", confirmed: "مؤكد", shipped: "قيد التوصيل", completed: "مكتمل", cancelled: "ملغي" };

function AdminContent() {
  const { user } = useAuth();
  const enabled = user?.role === "admin";
  const utils = trpc.useUtils();
  const { data: stats } = trpc.admin.stats.useQuery(undefined, { enabled });
  const { data: productRows } = trpc.admin.products.useQuery(undefined, { enabled });
  const { data: orderRows } = trpc.admin.orders.useQuery(undefined, { enabled });
  const updateStatus = trpc.admin.updateOrderStatus.useMutation({ onSuccess: async () => { await utils.admin.orders.invalidate(); await utils.admin.stats.invalidate(); toast.success("تم تحديث حالة الطلب"); }, onError: (e) => toast.error(e.message) });
  const toggleProduct = trpc.admin.toggleProduct.useMutation({ onSuccess: async () => { await utils.admin.products.invalidate(); await utils.products.list.invalidate(); toast.success("تم تحديث المنتج"); }, onError: (e) => toast.error(e.message) });
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ slug: "", name: "", shortDescription: "", description: "", price: "", imageUrl: "", badge: "", stock: "25" });
  const createProduct = trpc.admin.createProduct.useMutation({ onSuccess: async () => { await utils.admin.products.invalidate(); await utils.products.list.invalidate(); setShowForm(false); setForm({ slug: "", name: "", shortDescription: "", description: "", price: "", imageUrl: "", badge: "", stock: "25" }); toast.success("تمت إضافة المنتج"); }, onError: (e) => toast.error(e.message) });
  const submitProduct = (e: React.FormEvent) => { e.preventDefault(); createProduct.mutate({ ...form, stock: Number(form.stock) }); };
  return <div className="admin-main"><header className="admin-header"><div><div className="section-kicker">إدارة جرانولي</div><h1>لوحة التحكم</h1><p>نظرة واضحة على المتجر والطلبات والعملاء.</p></div><button className="btn-primary" onClick={() => setShowForm((v) => !v)}><PackagePlus size={17} /> {showForm ? "إغلاق النموذج" : "إضافة منتج"}</button></header>{showForm && <form className="admin-panel" onSubmit={submitProduct}><h2>منتج جديد</h2><div className="grid md:grid-cols-2 gap-4"><div className="field"><label>اسم المنتج</label><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="field"><label>الرابط المختصر</label><input required value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} placeholder="new-flavor" /></div><div className="field"><label>الوصف المختصر</label><input required value={form.shortDescription} onChange={(e) => setForm({ ...form, shortDescription: e.target.value })} /></div><div className="field"><label>السعر (ر.ع)</label><input required value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} placeholder="2.500" /></div><div className="field md:col-span-2"><label>الوصف الكامل</label><textarea required rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="field md:col-span-2"><label>رابط الصورة</label><input required type="url" value={form.imageUrl} onChange={(e) => setForm({ ...form, imageUrl: e.target.value })} placeholder="https://..." /></div><div className="field"><label>الشارة</label><input value={form.badge} onChange={(e) => setForm({ ...form, badge: e.target.value })} placeholder="الأكثر طلباً" /></div><div className="field"><label>المخزون</label><input required type="number" min={0} value={form.stock} onChange={(e) => setForm({ ...form, stock: e.target.value })} /></div></div><button className="btn-dark mt-5" disabled={createProduct.isPending}>{createProduct.isPending ? "جارٍ الحفظ..." : "حفظ المنتج"}</button></form>}
    <section className="stats-grid"><div className="stat-card"><Users className="text-[#b88946]" /><span>العملاء</span><strong>{stats?.users ?? "—"}</strong></div><div className="stat-card"><Box className="text-[#b88946]" /><span>المنتجات النشطة</span><strong>{stats?.products ?? "—"}</strong></div><div className="stat-card"><ClipboardList className="text-[#b88946]" /><span>كل الطلبات</span><strong>{stats?.orders ?? "—"}</strong></div><div className="stat-card"><CircleDollarSign className="text-[#b88946]" /><span>الإيراد المكتمل</span><strong className="!text-2xl">{stats ? `${Number(stats.revenue).toFixed(3)} ر.ع` : "—"}</strong></div></section>
    <section className="admin-panel"><div className="flex justify-between items-center gap-3 mb-4"><div><h2>الطلبات الأخيرة</h2><p className="text-sm text-[#766b5d] m-0">تابعي حالة كل طلب من لحظة وصوله حتى الإكمال.</p></div><BarChart3 className="text-[#b88946]" /></div><table className="admin-table"><thead><tr><th>رقم الطلب</th><th>العميل</th><th>الإجمالي</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>{orderRows?.length ? orderRows.map(({ order, userName, userEmail }) => <tr key={order.id}><td>#{order.id}</td><td><strong>{userName || "—"}</strong><div className="text-xs text-[#766b5d]">{userEmail || ""}</div></td><td>{Number(order.total).toFixed(3)} ر.ع</td><td>{new Date(order.createdAt).toLocaleDateString("ar-OM")}</td><td><select className="status-select" value={order.status} onChange={(e) => updateStatus.mutate({ id: order.id, status: e.target.value as any })}>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></td></tr>) : <tr><td colSpan={5} className="text-center text-[#766b5d] py-8">لا توجد طلبات بعد.</td></tr>}</tbody></table></section>
    <section className="admin-panel"><div className="flex justify-between items-center mb-4"><div><h2>إدارة المنتجات</h2><p className="text-sm text-[#766b5d] m-0">فعّلي أو أخفي أي منتج من المتجر بضغطة.</p></div><CheckCircle2 className="text-[#b88946]" /></div><table className="admin-table"><thead><tr><th>المنتج</th><th>السعر</th><th>المخزون</th><th>الظهور</th><th /></tr></thead><tbody>{productRows?.map((product) => <tr key={product.id}><td className="flex items-center gap-3"><img src={product.imageUrl} className="w-12 h-12 rounded-xl object-cover" alt="" /><span>{product.name}</span></td><td>{Number(product.price).toFixed(3)} ر.ع</td><td>{product.stock}</td><td>{product.active ? "ظاهر" : "مخفي"}</td><td><button className="btn-ghost !px-3 !py-2 !text-xs" onClick={() => toggleProduct.mutate({ id: product.id, active: product.active ? 0 : 1 })}><ChevronDown size={14} /> {product.active ? "إخفاء" : "إظهار"}</button></td></tr>)}</tbody></table></section>
  </div>;
}

export default function Admin() { return <DashboardLayout><AdminContent /></DashboardLayout>; }
