import { startLogin } from "@/const";
import { ArrowRight, LockKeyhole, Mail, UserRound } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import StoreHeader from "@/components/StoreHeader";

export default function Auth() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils(); const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const login = trpc.auth.login.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/"); }, onError: (e) => setError(e.message) });
  const register = trpc.auth.register.useMutation({ onSuccess: async () => { await utils.auth.me.invalidate(); navigate("/"); }, onError: (e) => setError(e.message) });
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(""); if (mode === "login") login.mutate({ email, password }); else register.mutate({ name, email, password }); };
  const pending = login.isPending || register.isPending;
  return <div className="site-shell"><StoreHeader /><main className="auth-wrap"><section className="auth-card"><div className="text-center mb-6"><div className="brand justify-center mb-5"><span className="brand-mark" /><span>GRANOLI</span></div><h1>{mode === "login" ? "أهلاً بعودتك" : "انضمي إلى جرانولي"}</h1><p>{mode === "login" ? "دخّلي بياناتك لتكملي طلبك." : "أنشئي حساباً واحفظي طلباتك في مكان واحد."}</p></div><div className="auth-switch"><button className={mode === "login" ? "active" : ""} onClick={() => { setMode("login"); setError(""); }}>تسجيل الدخول</button><button className={mode === "register" ? "active" : ""} onClick={() => { setMode("register"); setError(""); }}>حساب جديد</button></div><form className="form-stack" onSubmit={submit}>{mode === "register" && <div className="field"><label>الاسم</label><div className="relative"><UserRound className="absolute right-3 top-3.5 text-[#b88946]" size={17} /><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="مثال: سارة" className="pr-10" /></div></div>}<div className="field"><label>البريد الإلكتروني</label><div className="relative"><Mail className="absolute right-3 top-3.5 text-[#b88946]" size={17} /><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@example.com" className="pr-10" /></div></div><div className="field"><label>كلمة المرور</label><div className="relative"><LockKeyhole className="absolute right-3 top-3.5 text-[#b88946]" size={17} /><input required type="password" minLength={6} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="6 أحرف على الأقل" className="pr-10" /></div></div>{error && <div className="rounded-xl bg-red-50 text-red-700 text-sm p-3">{error}</div>}<button className="btn-dark w-full" disabled={pending}>{pending ? "لحظات..." : mode === "login" ? "دخول آمن" : "إنشاء الحساب"}</button></form><div className="flex items-center gap-3 my-5 text-xs text-[#766b5d]"><span className="h-px bg-[#e5dac9] flex-1" /> أو <span className="h-px bg-[#e5dac9] flex-1" /></div><button className="btn-ghost w-full" onClick={() => startLogin()}>المتابعة بحساب Manus</button><Link href="/products" className="flex items-center justify-center gap-2 text-sm text-[#766b5d] mt-6"><ArrowRight size={15} /> العودة للتسوق</Link></section></main></div>;
}
